Proyecto_RH/Capacitación_MVC_ABM/web/Models/ErrorViewModel.cs
using System;

namespace web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Proyecto_RH/Capacitación_MVC_ABM/web/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;

namespace web.Controllers
{
    public class ClienteController : Controller
    {
        public IActionResult Consulta()
        {
            return View();
        }

        public IActionResult Agregar()
        {
            return View("Agregar");
        }

        public IActionResult Editar(int id)
        {
            ViewBag.Id = id;

            return View("Editar");
        }

    }
}

Proyecto_RH/Capacitación_MVC_ABM/web/Controllers/FichaSepelioController.cs
using Microsoft.AspNetCore.Mvc;

namespace web.Controllers
{
    public class FichaSepelioController : Controller
    {
        public IActionResult Consulta()
        {
            return View();
        }

        public IActionResult Agregar()
        {
            return View("Agregar");
        }

        public IActionResult Editar(int id)
        {
            ViewBag.Id = id;

            return View("Editar");
        }

    }
}

Proyecto_RH/Capacitación_MVC_ABM/web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Proyecto_RH/Capacitación_MVC_ABM/web/Views/Cliente/Agregar.cshtml
@{
    ViewData["Title"] = "Agregar Cliente";
}

<h2>@ViewData["Title"].</h2>
<p>Complete el siguiente formulario para agregar un nuevo cliente:</p>

<form>


    <div class="form-group">
        <label for="exampleFormControlInput1">Nombre</label>
        <input id="nombre" required type="text" class="form-control" id="exampleFormControlInput1"
            placeholder="Ingrese su Nombre">

    </div>
    <div id="form-apellido" class="form-group">
        <label for="exampleFormControlInput1">Apellido</label>
        <input id="apellido" required type="texto" class="form-control" id="exampleFormControlInput1"
            placeholder="Ingrese su apellido">
    </div>
    <div id="form-correo" class="form-group">
        <label for="exampleFormControlInput1">Correo</label>
        <input id="correo" required type="email" class="form-control" id="exampleFormControlInput1"
            placeholder="nombre@correo.com">
    </div>
    <div id="form-estado" class="form-group">
        <label for="exampleFormControlSelect1">Seleccione un estado</label>
        <select id="estado" required class="form-control" id="exampleFormControlSelect1">
            <option>3</option>
            <option>4</option>
            <option>5</option>
            <option>6</option>

        </select>
    </div>

    <button id="btnSubmit" type="submit" class="btn btn-primary">Agregar</button>

</form>
<br>
<div id="errores"></div>


@section scripts {
<script>

    $("#btnSubmit").click((e) => postCliente(e))

    const toastPrompt = () => {

        const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 1000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.addEventListener('mouseenter', Swal.stopTimer)
                toast.addEventListener('mouseleave', Swal.resumeTimer)
            }
        })

        Toast.fire({
            icon: 'success',
            title: 'Cliente agregado',

        })
    }

    const mostrarAlertas = (respuesta) => {
        $(".alert").remove();

        if (respuesta.responseJSON.errors.Nombre) {
            for (var i = 0; i < respuesta.responseJSON.errors.Nombre.length; i++) {
                $("#errores").append(`<div  class="alert alert-danger" role="alert">
                        ${respuesta.responseJSON.errors.Nombre[i]}</div>`)
            }
        }
        if (respuesta.responseJSON.errors.Apellido) {
            for (var i = 0; i < respuesta.responseJSON.errors.Apellido.length; i++) {
                $("#errores").append(`<div  class="alert alert-danger" role="alert">
                        ${respuesta.responseJSON.errors.Apellido[i]}</div>`)
            }
        }
        if (respuesta.responseJSON.errors.Correo) {
            for (var i = 0; i < respuesta.responseJSON.errors.Correo.length; i++) {

                $("#errores").append(`<div  class="alert alert-danger" role="alert">
            ${respuesta.responseJSON.errors.Correo[0]}</div>`);
            }
        }
        if (respuesta.responseJSON.errors.Estado) {
            for (var i = 0; i < respuesta.responseJSON.errors.Estado.length; i++) {

                $("#errores").append(`<div  class="alert alert-danger" role="alert">
            ${respuesta.responseJSON.errors.Estado[0]}</div>`);
            }
        }

    }

    const postCliente = (e) => {
        e.preventDefault();
        const nombre = $("#nombre").val()
        const apellido = $("#apellido").val()
        const correo = $("#correo").val()
        const estado = parseInt($("#estado").val())

        let datos = { nombre, apellido, correo, estado }

        $.ajax({
            url: "https://localhost:5001/api/Cliente",
            type: "POST",
            data:
                JSON.stringify(datos),
            contentType: "application/json",
        }).done(function (respuesta) {
            $("#btnSubmit").prop("disabled", true)
            toastPrompt()
            setTimeout(function () { location.href = "consulta" }, 1000);
        }).fail((respuesta) => mostrarAlertas(respuesta));
    }

</script>
}

Proyecto_RH/Capacitación_MVC_ABM/web/Views/Cliente/Consulta.cshtml
@{
    ViewData["Title"] = "Clientes";
}




<a type="submit" class="btn btn-success float-right" asp-area="" asp-controller="Cliente" asp-action="Agregar">+ Cliente</a>
<br>
<h3>Buscar Clientes</h3>
<label for="exampleInputEmail1">Filtros:</label>

<form class="form-inline">
    <div class="form-group mb-2">
        <input type="text" class="form-control" id="nombreCliente" aria-describedby="emailHelp"
            placeholder="Ingrese un nombre">
@*         <small id="emailHelp" class="form-text text-muted">Ingrese un nombre.</small>
 *@    </div>

    <div class="form-group mx-sm-3 mb-2">
        @* <label for="exampleInputEmail1">Buscar por apellido</label> *@
        <input type="text" class="form-control" id="apellidoCliente" aria-describedby="emailHelp"
            placeholder="Ingrese un apellido">
@*         <small id="emailHelp" class="form-text text-muted">Ingrese un apellido.</small>
 *@    </div>

    <div class="form-group mx-sm-3 mb-2" >
        @* <label for="exampleInputEmail1">Buscar por correo</label> *@
        <input type="email" class="form-control" id="correoCliente" aria-describedby="emailHelp"
            placeholder="Ingrese un correo">
@*         <small id="emailHelp" class="form-text text-muted">Ingrese un correo.</small>
 *@    </div>



<br>

</form>
    <div id="form-estado" class="form-group">         
        
@*         <label for="exampleFormControlSelect1">Seleccione un estado</label>
 *@        <select id="estadoCliente" required class="form-control "style="width:auto;" id="exampleFormControlSelect1">
            <option>3</option>
            <option>4</option>
            <option>5</option>
            <option>6</option>

        </select>
         <small id="emailHelp" class="form-text text-muted">Seleccione un estado.</small>
    </div>
    <div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="estadoCheckBox">
  <label class="form-check-label" for="flexCheckDefault">
    Incluir estado
  </label>
</div>
    <button id="btnSubmit" type="submit" class="btn btn-primary mb-2">Buscar</button>

<br>


<table id="tabla" class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellido</th>
            <th scope="col">Estado</th>
            <th scope="col">Correo</th>
            <th scope="col">Acciones</th>
            
        </tr>
    </thead>
    <tbody id="cuerpo-tabla">
    </tbody>
</table>




@section scripts {
<script>

    const limpiarTabla = ()=>{
        var table = document.getElementById("tabla");
        while (table.rows.length > 1) {
            table.deleteRow(1);
        }
    }

    const renderTabla = (value)=>{
            $("#cuerpo-tabla").append(`<tr>        
                <th scope="row">${value.id}</th>
                 <td>${value.nombre}</td> 
                 <td>${value.apellido}</td> 
                 <td>${value.estado}</td> 
                 <td>${value.correo}</td> 
                <td>
                <button onclick="eliminar(${value.id});" id="btnEliminar"  class="btn btn-danger">Eliminar</button>
                    <a id="btnEditar"  class="btn btn-info" href="/Cliente/Editar?id=${value.id}" >Editar</a>
               </td>
                </tr>`);
    }

    const deleteCliente = (id)=>{
            $.ajax({
                    url: "https://localhost:5001/api/Cliente/" + id,
                    method: 'DELETE'
                }).done(function (respuesta) {
                    $.each(respuesta, function (index, value) {
                        renderTabla(value);
                    });
                }).fail(function () {
                    console.log("ERROR!");
                });
    }
    const eliminar = (id) => {
        Swal.fire({
            title: '¿Estás seguro que deseas eliminar este registro?',
            text: "No será capaz de revertir esto!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Eliminar!',
            cancelButtonText:"Cancelar"
        }).then((result) => {
            if (result.isConfirmed) {
                
                limpiarTabla();
                deleteCliente(id);
                Swal.fire(
                    '¡Eliminado!',
                    'El registro se eliminó cone éxito.',
                    'success'
                )
            }
        })




    }
    const buscarClientes = (e)=>{
        e.preventDefault();
        limpiarTabla();
        var table = document.getElementById("tabla");
        var nombre = document.getElementById("nombreCliente").value;
        var apellido = document.getElementById("apellidoCliente").value;
        var correo = document.getElementById("correoCliente").value;
        var estado =""
        var parteUrlConEstado = ""
        if($('#estadoCheckBox').is(":checked")){
            estado = parseInt($("#estadoCliente").val())
            parteUrlConEstado =`&estado=${estado}`

        }

        $.ajax({
            url: `http://localhost:5001/api/Cliente?Nombre=${nombre}&Apellido=${apellido}&Correo=${correo}`+parteUrlConEstado,
            method: 'GET'
        }).done(function (respuesta) {
            $.each(respuesta, function (index, value) {
                renderTabla(value);
            });
        }).fail(function () {
            console.log("ERROR!");
        });


    }

    const getTodosLosClientes = ()=>{
        $.ajax({
            url: "https://localhost:5001/api/Cliente",
            method: 'GET'
            
        }).done(function (respuesta) {
            
            $.each(respuesta, function (index, value) {
                renderTabla(value);
            });
        }).fail(function () {
            console.log("ERROR!");
        });
    }

    

    $("#btnSubmit").click( (e)=>buscarClientes(e))
    $(document).ready(getTodosLosClientes());


    



</script>
}

Proyecto_RH/Capacitación_MVC_ABM/web/Views/Cliente/Editar.cshtml
@{
    ViewData["Title"] = "Editar cliente";
}




<h2>@ViewData["Title"].</h2>
<p>Edite el siguiente formulario para actualizar el cliente:</p>

<form>
    <div class="form-group">
        <label for="exampleFormControlInput1">Nombre</label>
        <input id="nombre" required type="text" class="form-control" id="exampleFormControlInput1"
            placeholder="Ingrese su Nombre">

    </div>
    <div id="form-apellido" class="form-group">
        <label for="exampleFormControlInput1">Apellido</label>
        <input id="apellido" required type="texto" class="form-control" id="exampleFormControlInput1"
            placeholder="Ingrese su apellido">
    </div>
    <div id="form-correo" class="form-group">
        <label for="exampleFormControlInput1">Correo</label>
        <input id="correo" required type="email" class="form-control" id="exampleFormControlInput1"
            placeholder="nombre@correo.com">
    </div>
    <div id="form-estado" class="form-group">
        <label for="exampleFormControlSelect1">Seleccione un estado</label>
        <select id="estado" required class="form-control" id="exampleFormControlSelect1">
            <option>3</option>
            <option>4</option>
            <option>5</option>
            <option>6</option>

        </select>
    </div>

    <button id="btnSubmit" type="submit" class="btn btn-primary">Actualizar</button>

</form>
<br>
<div id="errores"></div>




@section scripts {
<script>

    $("#btnSubmit").click((e) => putCliente(e))

    const putCliente = (e) => {
        e.preventDefault();
        const nombre = $("#nombre").val()
        const apellido = $("#apellido").val()
        const correo = $("#correo").val()
        const estado = parseInt($("#estado").val())

        let datos = { nombre, apellido, correo, estado }

        $.ajax({
            url: "https://localhost:5001/api/Cliente/" + @ViewBag.Id,
            type: "PUT",
            data:
                JSON.stringify(datos),
            contentType: "application/json",
        }).done(function (respuesta) {
            $("#btnSubmit").prop("disabled", true)
            toastPrompt()
            setTimeout(function () { location.href = "consulta" }, 1000);
        }).fail((respuesta) => mostrarAlertas(respuesta));
    }

    const mostrarAlertas = (respuesta) => {
        $(".alert").remove();

        if (respuesta.responseJSON.errors.Nombre) {
            for (var i = 0; i < respuesta.responseJSON.errors.Nombre.length; i++) {
                $("#errores").append(`<div  class="alert alert-danger" role="alert">
                        ${respuesta.responseJSON.errors.Nombre[i]}</div>`)
            }
        }
        if (respuesta.responseJSON.errors.Apellido) {
            for (var i = 0; i < respuesta.responseJSON.errors.Apellido.length; i++) {
                $("#errores").append(`<div  class="alert alert-danger" role="alert">
                        ${respuesta.responseJSON.errors.Apellido[i]}</div>`)
            }
        }
        if (respuesta.responseJSON.errors.Correo) {
            for (var i = 0; i < respuesta.responseJSON.errors.Correo.length; i++) {

                $("#errores").append(`<div  class="alert alert-danger" role="alert">
            ${respuesta.responseJSON.errors.Correo[0]}</div>`);
            }
        }
        if (respuesta.responseJSON.errors.Estado) {
            for (var i = 0; i < respuesta.responseJSON.errors.Estado.length; i++) {

                $("#errores").append(`<div  class="alert alert-danger" role="alert">
            ${respuesta.responseJSON.errors.Estado[0]}</div>`);
            }
        }

    }

    $("#btnSubmit").click((e) => postCliente(e))

    const toastPrompt = () => {

        const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 1000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.addEventListener('mouseenter', Swal.stopTimer)
                toast.addEventListener('mouseleave', Swal.resumeTimer)
            }
        })

        Toast.fire({
            icon: 'success',
            title: 'Cliente actualizado',

        })
    }

    const buscarClientes = () => {

        $.ajax({
            url: "https://localhost:5001/api/Cliente/?id=" + @ViewBag.Id ,
            method: 'GET'
        }).done(function (respuesta) {
            console.log(respuesta)
            $("#nombre").val(respuesta[0].nombre);
            $("#apellido").val(respuesta[0].apellido);
            $("#correo").val(respuesta[0].correo);
            $("#estado").val(respuesta[0].estado);
        }).fail(function () {
            console.log("ERROR!");
        });


    }
    $(document).ready(buscarClientes());

</script>
}

Proyecto_RH/Capacitación_MVC_ABM/web/Views/FichaSepelio/Consulta.cshtml
@{
    ViewData["Title"] = "Fichas";
}




<a type="submit" class="btn btn-success float-right" asp-area="" asp-controller="Cliente" asp-action="Agregar">Cargar una ficha nueva</a>
<br>
<h3>Buscar fichas</h3>
<label for="exampleInputEmail1">Filtros:</label>

<form class="form-inline">
    <div class="form-group mb-2">
        <input type="text" class="form-control" id="NombreExtinto" aria-describedby="emailHelp"
            placeholder="Ingrese un nombre:">
    </div>

    <div class="form-group mx-sm-3 mb-2">
        
        <input type="text" class="form-control" id="ApellidoExtinto" aria-describedby="emailHelp"
            placeholder="Ingrese un apellido">
   </div>

    <div class="form-group mx-sm-3 mb-2" >
        
        <input type="date" class="form-control" id="FechaFallecimiento" aria-describedby="emailHelp"
            placeholder="Ingrese una fecha">
   </div>
<br>

</form>

<button id="btnSubmit" type="submit" class="btn btn-primary mb-2">Buscar</button>

<br>


<table id="tabla" class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre extinto</th>
            <th scope="col">Apellido extinto</th>
            <th scope="col">Fecha Fallecimiento</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody id="cuerpo-tabla">
    </tbody>
</table>




@section scripts {
<script>

    const limpiarTabla = ()=>{
        var table = document.getElementById("tabla");
        while (table.rows.length > 1) {
            table.deleteRow(1);
        }
    }

    const renderTabla = (value)=>{
            debugger;
            $("#cuerpo-tabla").append(`<tr>        
                <th scope="row">${value.id}</th>
                 <td>${value.nombreExtinto}</td> 
                 <td>${value.apellidoExtinto}</td> 
                 <td>${value.fechaFallecimiento}</td> 
                <td>
                <button onclick="eliminar(${value.id});" id="btnEliminar"  class="btn btn-danger">Eliminar</button>
                    <a id="btnEditar"  class="btn btn-info" href="/Cliente/Editar?id=${value.id}" >Editar</a>
               </td>
                </tr>`);
    }

    const deleteFicha = (id)=>{
            $.ajax({
                    url: "https://localhost:5001/api/FichaSepelio" + id,
                    method: 'DELETE'
                }).done(function (respuesta) {
                    $.each(respuesta, function (index, value) {
                        renderTabla(value);
                    });
                }).fail(function () {
                    console.log("ERROR!");
                });
    }
    const eliminar = (id) => {
        Swal.fire({
            title: '¿Estás seguro que deseas eliminar este registro?',
            text: "No será capaz de revertir esto!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Eliminar!',
            cancelButtonText:"Cancelar"
        }).then((result) => {
            if (result.isConfirmed) {
                
                limpiarTabla();
                deleteFicha(id);
                Swal.fire(
                    '¡Eliminado!',
                    'El registro se eliminó con éxito.',
                    'success'
                )
            }
        })




    }
    const buscarFichas = (e)=>{
        e.preventDefault();
        limpiarTabla();
        debugger;
        var table = document.getElementById("tabla");
        var Nombre = document.getElementById("NombreExtinto").value;
        var Apellido = document.getElementById("ApellidoExtinto").value;
        var Fecha= document.getElementById("FechaFallecimiento").value;
        
        $.ajax({
            url: `http://localhost:5001/api/FichaSepelio?NombreExtinto=${Nombre}&Apellido=${Apellido}&FechaFallecimiento=${Fecha}`,
            method: 'GET'
        }).done(function (respuesta) {
            $.each(respuesta, function (index, value) {
                renderTabla(value);
            });
        }).fail(function () {
            console.log("ERROR!");
        });


    }

    const getTodasLasFichas = ()=>{
        $.ajax({
            url: "https://localhost:5001/api/FichaSepelio",
            method: 'GET'
        }).done(function (respuesta) {
            debugger;
            $.each(respuesta, function (index, value) {
                renderTabla(value);
            });
        }).fail(function () {
            console.log("ERROR!");
        });
    }
    
    $("#btnSubmit").click( (e)=>buscarFichas(e))
    $(document).ready(getTodasLasFichas());
</script>
}

Proyecto_RH/Capacitación_MVC_ABM/web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Proyecto_RH/Capacitación_MVC_ABM/web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet"/> 
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente"
                                asp-action="Consulta">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FichaSepelio"
                            asp-action="Consulta">Fichas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>